version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - ./init.sql:/init.sql
      - ./init_table.sql:/init_table.sql
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr & sleep 20 &&
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P YourStrong!Passw0rd -d master -i /init.sql -C &&
      sleep 20 && opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P YourStrong!Passw0rd -d item_management -i /init_table.sql -C &&
      tail -f /dev/null"